### ISSUE TITLE
As a developer, I want to have documentation for all source, so that PO is satisfied

### ISSUE THREAD

**Issue by metalmatze** [7Pros/circuit#73]
All developers need to document their implemented classes, functions etc.

**Comment by MetalMatze** [comment]
All developers need to document their implemented classes, functions etc.

**Comment by Gjum** [comment]
I'm wondering how intense the source code should be documented, as most of the current code doesn't get beyond the normal usage of Django.

I agree, however, that some functionality should be documented explicitly:
- mail confirmation and inactive accounts
- allowing/denying access to profile/post editing depending on logged in user
- maybe some user model fields

But the documentation for this doesn't have to be in the source code. It may be better off in a separate document or the wiki.

This should be done with the API in mind, for which we will also write documentation.

**Comment by juanecabellob** [comment]
Those are 2 different kinds of documentation, one is the technical documentation and the other is the end user manual. (Wikipedia entry: http://en.wikipedia.org/wiki/Software_documentation) 

We must cover both.

The documentation standards of the source code that i have think of are (using doxygen:):
- All files must be documented, having a **header** that will have the following things:
  - The file path
  - Our team as authors
  - The version of the file with the date it was changed
- All methods that expect a **parameter** must have a detailed definition of what is to be expected.
- All methods that have a **return value** must have a detailed definition of what will be returned.
- All methods that its use may be **hard to understand** should have a one-sentence definition of its use.

The end user manual must be done once the code is finished, covering all use of case-scenarios.

Just a reminder, about what is the source code documentation for, you may write your code and as you are working in your code you see everything logical and understandable, but if someone else is trying to use your code in order to get done part of theirs, it is easier to have some documented methods and files so it won't be a start from the scratch but knowing at least the crucial points. Having that in mind, I think the most the better, so we don't lose time understanding code.

_Edit: Formatting (@Gjum)_

**Comment by metalmatze** [comment]
For me the above said looks fine. I just think that this part is too much, since we have git.

> - All files must be documented, having a header that will have the following things:
>   - The file path
>   - Our team as authors
>   - The version of the file with the date it was changed

**Comment by juanecabellob** [comment]
I'm currently digging out more about doxygen, and if i'm not wrong, we need the file path to differentiate the documentation from file to file. However, i think that the  versioning, the team as authors, (and maybe the copyrights?) must be in the header, the versioning so we keep a number of the patch, update, etc.., the team as authors, so in case our code got copied we still have our rights and in case we put the copyrights it is self-explanatory :D

**Comment by juanecabellob** [comment]
And for those using PyCharm, it can be easily done that such a header be automatically generated. After I'm done with testing Doxygen, I can generate a PyCharm pre-configured template for the header, that after every file was created the headers be automatically there and after some small adjustments it's done. Only if it's wanted, obviously.

**Comment by Gjum** [comment]
Regarding the header, I agree with @MetalMatze - Git does the versioning, and the file path is implicit.
Putting that changing data into the header is an unnecessary additional effort.

However, putting the copyright notice (including the team) as the header would be fine, as it only changes once a year. IIRC some licenses even require this.

**Comment by juanecabellob** [comment]
Ok, I'm a bit further with Doxygen info, file path is not required as for the standard html output that it generates - which in my opinion it's just fine, but you can also let me know your opinion. Moreover, if you all agree about the versioning and file path, then I agree as well. 

As for general information, I have looked the code documentation from some other python projects and they mostly provide some brief description about the file, as "Model for whatever" or "URL router for the app" and so on.  If they don't, it is because the file is a bit more complex to understand doing a quick review. In that case, they write a short paragraph describing what's the file about. 

Having said that, I would include that kind of description in the header _BEFORE_ the copyright notice. What do you think?
